### ISSUE TITLE
Compatibility With Dynamic UI Themes

### ISSUE THREAD

**Issue by kaidesu** [rainglow/atom#1]
Hey there! First off, excellent work 🚀  I've been using your themes for years now.

One improvement that could be made to the Atom themes is adding support for dynamic UI themes (such as One Dark and Material UI). These type of UI themes make use of the syntax theme's `syntax-variables.less` file to determine matching colors.

- [Documentation](http://flight-manual.atom.io/hacking-atom/sections/creating-a-theme/#theme-variables)
- [Example PR in another repo](https://github.com/carloe/spacegray-base16-ocean-dark/pull/13)

![screen shot 2018-01-02 at 2 54 41 pm](https://user-images.githubusercontent.com/355659/34503394-eb506c98-efcc-11e7-9fd1-9bf023db8ca1.png)

**Comment by daylerees** [comment]
Ah interesting! Didn't know they read that file. Thanks for the thorough issue content. I'll see if I can sort it out soon. :)

**Comment by daylerees** [comment]
This should be fixed in version `1.5.3`. Thanks for your help! :)

**Comment by kaidesu** [comment]
Beautiful!
